services:
  presenton:
    image: ${PRESENTON_IMAGE:-ghcr.io/presenton/presenton:latest}
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8000:8000"
    volumes:
      - ./app_data/chroma:/app/servers/fastapi/chroma